name: autin
channels:
  - conda-forge
  - menpo
dependencies:
  - python
  - numpy
  - matplotlib
  - scipy
  - sympy
  -
  - mpmath
  - uncertainties
  - pint
  - ipywidgets
  - jupyter_contrib_nbextensions
  - ffmpeg
  - opencv3
  - scikit-learn
  - scikit-image
 
